// This map links the animal names generated by the Gemini API to the local image files.
// Please create an 'assets' folder and add the corresponding images with these exact filenames.

export const animalImageMap: Record<string, string> = {
  'Dog': 'assets/german-shepherd.jpg',
  'Elephant': 'assets/elephant.jpg',
  'Arctic Wolf': 'assets/placeholder.jpg', // Image not provided in collage
  'Dove': 'assets/placeholder.jpg',      // Image not provided in collage
  'Dolphin': 'assets/dolphin.jpg',
  'Eagle': 'assets/eagle.jpg',
  'Fox': 'assets/fox.jpg',
  'Octopus': 'assets/placeholder.jpg',   // Image not provided in collage
  'Cat': 'assets/cheetah.jpg',           // Using cheetah image for 'Cat' persona
  'Sea Turtle': 'assets/sea-turtle.jpg',
  'Owl': 'assets/owl.jpg',
};
