// This map links the animal names generated by the Gemini API to the local image files.
// Please create an 'assets' folder and add the corresponding images with these exact filenames.

export const animalImageMap: Record<string, string> = {
  'Dog': 'assets/dog1.png',
  'Elephant': 'assets/elephant.jpg',
  'Arctic Wolf': 'assets/artic.jpg', // Image not provided in collage
  'Dove': 'assets/placeholder.jpg',      // Image not provided in collage
  'Dolphin': 'assets/dolphin.png',
  'Eagle': 'assets/eagle.png',
  'Fox': 'assets/Fox.png',
  'Octopus': 'assets/octopus.png',   // Image not provided in collage
  'Cat': 'assets/cat.png',           // Using cheetah image for 'Cat' persona
  'Sea Turtle': 'assets/Sea_Turtle.png',
  'Owl': 'assets/owl.png',
};
